services:
  jaeger:
    image: jaegertracing/jaeger:2.15.1
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # UI
      - "4318:4318"   # OTLP/HTTP
      - "4317:4317"   # OTLP/gRPC
    networks:
      - tracing-network

networks:
  tracing-network:
    driver: bridge
